CREATE TABLE sale_records (
  SaleRecordId INTEGER PRIMARY KEY AUTOINCREMENT,
  EmployeeId INTEGER NOT NULL,
  InvoiceId INTEGER NOT NULL,
  FOREIGN KEY (EmployeeId) REFERENCES employees (EmployeeId) 
			ON DELETE CASCADE ON UPDATE NO ACTION,
  FOREIGN KEY (InvoiceId) REFERENCES invoices (InvoiceId) 
			ON DELETE CASCADE ON UPDATE NO ACTION		
)