export const ENTER_EMPLOYEE_EDITING = 'ENTER_EMPLOYEE_EDITING'
export const EMPLOYEE_LOADED = 'EMPLOYEE_LOADED'
export const OUTOF_EMPLOYEE_EDITING = 'OUTOF_EMPLOYEE_EDITING'

export const NORTHWIND_TAB_CHANGED = 'NORTHWIND_TAB_CHANGED'

export const ENTER_CUSTOMER_EDITING = 'ENTER_CUSTOMER_EDITING'
export const OUTOF_CUSTOMER_EDITING = 'OUT_CUSTOMER_EDITING'

export const ORDER_LOAD_STARTED = 'ORDER_LOAD_STARTED'
export const ORDER_LOAD_COMPELED = 'ORDER_LOAD_COMPELED'
export const ORDERDETAILS_LOAD_COMPELED = 'ORDERDETAILS_LOAD_COMPELED'